USE [master]
GO

/****** Object:  Database [DB54]    Script Date: 4/27/2019 10:55:38 PM ******/
CREATE DATABASE [DB54]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB54', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\DB54.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB54_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\DB54_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DB54] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB54].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB54] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB54] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB54] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB54] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB54] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB54] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB54] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB54] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB54] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB54] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB54] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB54] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB54] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB54] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB54] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB54] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB54] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB54] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB54] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB54] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB54] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB54] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB54] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB54] SET  MULTI_USER 
GO

ALTER DATABASE [DB54] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB54] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB54] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB54] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DB54] SET  READ_WRITE 
GO

