//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SETQUIZ
    {
        public int QUIZ_ID { get; set; }
        public Nullable<System.DateTime> QUIZ_DATE { get; set; }
        public Nullable<int> QUIZ_FK_STU { get; set; }
        public string QUIZ_NAME { get; set; }
        public Nullable<int> QUIZ_STD_SCORE { get; set; }
    }
}
